[package]
name = "admin-authority"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[package.metadata.spel]
extension_attr = "admin_authority"

[[package.metadata.spel.inject]]
  wrapper = "admin_initialize"

[[package.metadata.spel.inject.account]]
  name = "admin_config"
  seed = [{ const = "admin_config" }]

[[package.metadata.spel.inject.account]]
  name = "caller"
  signer = true

[[package.metadata.spel.inject]]
wrapper = "require_admin"

  [[package.metadata.spel.inject.account]]
  name = "admin_config"
  seed = { const = "admin_config" }

  [[package.metadata.spel.inject.account]]
  name = "caller"
  signer = true

[package.metadata.spel.embedded]
skip = ["admin_initialize"]
state_type = "admin_authority::AdminConfig"
anchor_attr = "admin_initialize"
anchor_role = "admin_config"

[[package.metadata.spel.bound_args]]
arg = "offset"
from = "offset"
default = 0

[dependencies]
borsh = { version = "1", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
spel-framework = { git = "https://github.com/mmlado/spel.git", rev = "7b954dbb572f611fbe5ebaa00b75aaa029803e3b" }
admin-authority-macros  = { path = "../admin-authority-macros"}
authority = { git = "https://github.com/mmlado/spel-authority.git", rev = "869249d197121fb667a744e216df9a3b76c3d764", package = "spel-authority" }

[dev-dependencies]
spel-framework-core = { git = "https://github.com/mmlado/spel.git", rev = "7b954dbb572f611fbe5ebaa00b75aaa029803e3b", features = ["idl-gen"] }
